name: pyopp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=2.0
  - pandas
  - matplotlib
  - jupyterlab
  - pre-commit
  - sphinx
  - sphinx-automodapi
  - sphinx-copybutton
  - pydata-sphinx-theme
  - numpydoc
