name: pyopp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy>=2.0
  - pandas
  - matplotlib
  - jupyter
  - notebook
  - ipython
  - pre-commit
  - nbstripout
  - sphinx
  - sphinx-automodapi
  - sphinx-copybutton
  - pydata-sphinx-theme
  - sphinx-design
  - colour
  - numpydoc
  - black
  - sphinx
  - pip:
    - -e .
